In [31]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import LabelEncoder 

In [32]:
# Let us create the Data-Frame for above 
X=pd.DataFrame({'LikesExercising':[False,False,False,True,False,True,True,True,True],
                'GotoGym':[True,True,True,True,True,False,True,False,False],
                 'DrivesCar':[True,False,False,True,True,False,True,False,True]})
y=pd.Series(name='Age',data=[14,15,16,26,36,50,69,72,74])

In [33]:
# Let us encode true and false to number value 0 and 1
LE=LabelEncoder()
X['LikesExercising']=LE.fit_transform(X['LikesExercising'])
X['GotoGym']=LE.fit_transform(X['GotoGym'])
X['DrivesCar']=LE.fit_transform(X['DrivesCar'])

In [34]:
#We will now see the effect of different numbers of estimators on MSE.
# 1) Let us now use  GradientBoostingRegressor with 2 estimators to train the model and to predict the age for the same inputs. 
gb = GradientBoostingRegressor(n_estimators=2)

In [35]:
gb.fit(X, y)

GradientBoostingRegressor(n_estimators=2)

In [36]:
y_pred = gb.predict(X)
y_pred

array([38.23 , 36.425, 36.425, 42.505, 38.23 , 45.07 , 42.505, 45.07 ,
       47.54 ])

In [37]:
# MSE for two estimators
(sum((y - y_pred)**2))/len(y)

432.48205555555546

In [38]:
# 2) Let us now use GradientBoostingRegressor with 3 estimators to train the model and to predict the age for the same inputs. 
gb2 = GradientBoostingRegressor(n_estimators=3)

In [39]:
gb2.fit(X, y)

GradientBoostingRegressor(n_estimators=3)

In [40]:
y_pred2 = gb2.predict(X)
y_pred2

array([36.907 , 34.3325, 34.3325, 43.0045, 36.907 , 46.663 , 43.0045,
       46.663 , 50.186 ])

In [41]:
#Following code is used to find out MSE of prediction with Gradient boosting algorithm having estimator 3.
(sum((y - y_pred2)**2))/len(y)

380.05602055555556

In [42]:
# 3) Let us now use GradientBoostingRegressor with 50 estimators to train the model and to predict the age for the same inputs.
gb3 = GradientBoostingRegressor(n_estimators=50)

In [43]:
gb3.fit(X, y)

GradientBoostingRegressor(n_estimators=50)

In [46]:
y_pred3 = gb3.predict(X)
y_pred3

array([25.08417833, 15.63313919, 15.63313919, 47.46821839, 25.08417833,
       60.89864242, 47.46821839, 60.89864242, 73.83164334])

In [47]:
(sum((y - y_pred3)**2))/len(y)

156.5667260994211

Finding the best estimator with GridSearchCV

In [48]:
from sklearn.model_selection import GridSearchCV

In [49]:
model = GradientBoostingRegressor()

In [50]:
params = {'n_estimators':range(1,200)}
grid = GridSearchCV(estimator=model,cv=2,param_grid=params,scoring='neg_mean_squared_error')

In [51]:
grid.fit(X, y)

GridSearchCV(cv=2, estimator=GradientBoostingRegressor(),
             param_grid={'n_estimators': range(1, 200)},
             scoring='neg_mean_squared_error')

In [53]:
grid.best_estimator_

GradientBoostingRegressor(n_estimators=19)

In [54]:
gb = grid.best_estimator_
gb.fit(X, y)

GradientBoostingRegressor(n_estimators=19)

In [ ]:
y_pred = gb.predict(X)
