In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("E:\Programming\Machine Learning\ML Algorithams\Saving Model\homeprices.csv")

In [3]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression()

In [8]:
model.fit(df[['area']], df.price)

LinearRegression()

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

C:\Users\harik\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Model To a File Using Python Pickle

In [12]:
import pickle

In [13]:
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

Load Saved Model

In [14]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [15]:
mp.coef_

array([135.78767123])

In [16]:
mp.intercept_

180616.43835616432

In [17]:
model.predict([[5000]])

C:\Users\harik\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Trained Model Using joblib

In [18]:
import joblib

In [19]:
joblib.dump(model, 'model_joblib')

['model_joblib']

Load Saved Model

In [20]:
mj = joblib.load('model_joblib')

In [21]:
mj.coef_

array([135.78767123])

In [22]:
mj.intercept_

180616.43835616432

In [23]:
mj.predict([[5000]])

C:\Users\harik\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])